name: causal_inference

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
  train-model:
    needs: deploy-runner
    # runs-on: [self-hosted, cml-runner]
    runs-on: ubuntu-latest

    # container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
